#SPDX-License-Identifier: MIT-0
---
# tasks file for certbot
- name: Install certbot nginx python3
  apt:
    name: 
      - python3-certbot-nginx
    state: latest

- name: Generate SSL certificate with Nginx integration
  ansible.builtin.command: >-
    certbot --nginx
    --non-interactive
    --agree-tos
    --email lamanirmal27@gmail.com
    --redirect
    --staple-ocsp
    -d {{ item }}
  loop: "{{ my_domains }}"
  register: certbot_result # Register the output for checking
  changed_when: >- # Only report changed if a new cert was issued or renewed
    'Successfully received certificate.' in certbot_result.stdout or
    'Certificate not yet due for renewal; still operating' not in certbot_result.stdout
  notify: restart nginx # Nginx needs to be reloaded after Certbot modifies its config
