#SPDX-License-Identifier: MIT-0
---
# tasks file for php
- name: Install PHP packages
  ansible.builtin.package:
    name: "{{ php_modules }}"
    state: present
    update_cache: yes

- name: Ensure PHP service is running
  ansible.builtin.service:
    name: php8.3-fpm
    state: started
    enabled: yes